repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
        exclude: '\.json$'
      - id: check-yaml
        exclude: '\.json$'
      - id: end-of-file-fixer
        exclude: '\.json$'
      - id: trailing-whitespace
        exclude: '\.json$'
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--line-length=120", ]
        exclude: '\.json$'
      - id: isort
        name: isort (cython)
        types: [cython]
        exclude: '\.json$'
      - id: isort
        name: isort (pyi)
        types: [pyi]
        exclude: '\.json$'
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
        args: [--line-length=120]
        exclude: '\.json$'
